{{- if .Values.global.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.imagePullSecret.name}}
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecret.encodedsecret}}
type: kubernetes.io/dockerconfigjson
{{- end }}