---

- name: base64 encoding registry credential
  shell: >
    echo -ne '{{ registry_username }}:{{ registry_password }}' | base64 -w 0
  register: base64encoded
  failed_when: base64encoded.failed

- set_fact:
    pullsecret: "{{ lookup('file', '{{ pullsecret_path }}') }}"

- copy:
    content: "{{ pullsecret }}"
    dest: "./pullsecret.json"

- shell: >
    cat ./pullsecret.json
    | jq '. .auths += {"{{ local_registry_uri }}": {"auth":
    "{{ base64encoded.stdout }}","email": "{{ hostname }}@samsung.com"}}'
    | jq -c . > {{ pullsecret_bundle }} && rm -f ./pullsecret.json
