apiVersion: v1
description: DEPRECATED Host your own Helm Chart Repository
name: registrycleanup
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/helm/registrycleanup
icon: https://raw.githubusercontent.com/helm/registrycleanup/master/logo2.png
keywords:
  - registrycleanup
deprecated: true

