{{- if and .Values.apigateway.clusterRbac.create (not .Values.apigateway.controller.scope.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.apigateway.controller.label }}
    app.kubernetes.io/part-of: {{ .Values.apigateway.controller.label }}
    app: {{ template "apigateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "apigateway.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "apigateway.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "apigateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
