{{- if and .Values.apigateway.controller.stats.enabled .Values.apigateway.controller.metrics.enabled .Values.apigateway.controller.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "apigateway.controller.fullname" . }}
  {{- if .Values.apigateway.controller.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.apigateway.controller.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app: {{ template "apigateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.apigateway.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.apigateway.controller.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.apigateway.controller.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "apigateway.name" . }}
      component: "{{ .Values.apigateway.controller.name }}"
      release: {{ .Release.Name }}
{{- end }}
