{{- if gt .Values.apigateway.defaultBackend.replicaCount 1.0 }}
{{- if (semverCompare ">= 1.25.0-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "apigateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.apigateway.defaultBackend.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "apigateway.defaultBackend.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "apigateway.name" . }}
      release: {{ .Release.Name }}
      component: "{{ .Values.apigateway.defaultBackend.name }}"
  minAvailable: {{ .Values.apigateway.defaultBackend.minAvailable }}
{{- end }}
