{{- if .Values.apigateway.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.apigateway.controller.label }}
    app.kubernetes.io/part-of: {{ .Values.apigateway.controller.label }}
    app: {{ template "apigateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "apigateway.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ .Values.apigateway.controller.electionID }}-sb-leader-{{ .Values.apigateway.controller.ingressClass3 }}
      - {{ .Values.apigateway.controller.electionID }}-nb-leader-{{ .Values.apigateway.controller.ingressClass2 }}
    verbs:
      - add
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
      - ingresses
    verbs:
      - get
      - list
  {{- if .Values.apigateway.podSecurityPolicy.enabled }}
  - apiGroups:      ['extensions']
    resources:      ['podsecuritypolicies']
    verbs:          ['use']
    resourceNames:  [{{ template "apigateway.fullname" . }}]
    {{- end }}

    {{- end -}}
