apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.apigateway.controller.label }}
    app.kubernetes.io/part-of: {{ .Values.apigateway.controller.label }}
    app: {{ template "apigateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.apigateway.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "apigateway.controller.fullname" . }}-sb
data:
  enable-vts-status: "{{ .Values.apigateway.controller.stats.enabled }}"
{{- if .Values.apigateway.controller.headers }}
  proxy-set-headers: {{ .Release.Namespace }}/{{ template "apigateway.fullname" . }}-custom-headers
{{- end }}
{{- if .Values.apigateway.controller.config }}
{{ toYaml .Values.apigateway.controller.config | indent 2 }}
{{- end }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration-sb
  labels:kind: Role
data:
  worker-processes: "8"
  max-worker-connections: "4096"
  custom-http-errors: 404,405,413,503,401,403,504
  server-tokens: "false"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services-sb
  labels:
    app.kubernetes.io/name: {{ .Values.apigateway.controller.label }}
    app.kubernetes.io/part-of: {{ .Values.apigateway.controller.label }}
{{- if .Values.apigateway.tcp }}
data:
{{ toYaml .Values.apigateway.tcp | indent 2 }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services-sb
  labels:
    app.kubernetes.io/name: {{ .Values.apigateway.controller.label }}
    app.kubernetes.io/part-of: {{ .Values.apigateway.controller.label }}
{{- if .Values.apigateway.udp }}
data:
{{ toYaml .Values.apigateway.udp | indent 2 }}
{{- end }}
