{{- if .Values.multusConfiguration }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sco-sbi-nw
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "mode": "bridge",
    "master": "{{ .Values.multusConfiguration.sbInterface }}"
  }'
{{- end}}